stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: "$DOCKER_USERNAME/node-todo-cicd"

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .
  only:
    - main

push:
  stage: push
  script:
    - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME:latest
  only:
    - main

deploy:
  stage: deploy
  script:
    - chmod 600 $EC2_KEY
    - ssh -o StrictHostKeyChecking=no -i $EC2_KEY ubuntu@$EC2_HOST "
        docker pull $IMAGE_NAME:latest &&
        docker stop node-app || true &&
        docker rm node-app || true &&
        docker run -d -p 8000:8000 --name node-app $IMAGE_NAME:latest
      "
  only:
    - main
